
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1
  # version: "~>1.30"

managedNodeGroups:
  - name: roboshop
    instanceTypes: ["m5.large", "c3.large","c4.large","c5.large"]
    desiredCapacity: 3
    minSize: 2
    maxSize: 10
    spot: true